#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo $DIR

test() {
    mkdir -p $DIR/../build/source
    rsync -vr /home/patrikx3/Projects/patrikx3/openwrt-workspace/openwrt-insomnia/patches/source/feeds /home/patrikx3/Projects/patrikx3/openwrt-workspace/openwrt-insomnia/build/source
}

export -f test

