language: node_js
node_js:
- node
services:
- docker
before_script:
- npm install -g grunt-cli npm
- docker build -t patrikx3/openwrt-insomnia:base ./openwrt-base
script:
- docker build -t patrikx3/openwrt-insomnia .
env:
  global:
    secure: cE7LLpaebswrzkyAYEPYz0ILlE4ec39kV8Pi3hY32ni+HkDAUmSWl1kPAlX/4bxuTADzg+Z2cpWhVg3ov0jSuskAuXIjtmbDl9wSm2EU72BahDPr+ol+NsQfO6iIVvBTbNil2ptvJG4TTDZCzuXvoCKQhEt4RetlUpRQwPrUDqHJg4teuwaFSyv5+WQE3fkHYo65MRLxWPH4fMEcU9Osj6fwLoX5rWmdvMTEiTVcYxucxOQbmc12yNqWAxl1qnjKn7yJ0Oy8uA41TprGAXXF5RTnouS8tHYxc7Pnw5eYhdvHBdfka79tW6p36eE+v9yTxwzAN1N/klJ02zZkrjtUb5qkNNn94/AMQoPJIjjlqpwu0NuU1QNb3W/o/2v+Txvrlq0wvvyFZEpEwUn0EKePrJX0dpUko4QgzbVll8Ff4Ds0yOcvb9zLLhKi4HgXhtvl864Q/r9wJOhouc8YfI2z4Dn1Jyt4RGYLpkeAoxOK1ofboYX92TR12eBJc2iomfELliUt2x42FDTjDxU+e45yhH6LN0/RfQW0TREXM1bLlS9PzqS0D18ycGEkcsy4lfYpX1F/cLbysYAhLZN7q00OoMxeV2pP02TvumDRoTG2xIfgsZmvgW83vw3ekxvvj60GDEQSUO5ICw4Q17z0M/WHaY844iS2f6E45b5r4nht0vY=
