language: node_js
node_js:
  - "node"

services:
  - docker

before_script:
  - npm install grunt-cli -g
  - docker build -t patrikx3/openwrt-insomnia:base ./openwrt-base

script:
  - docker build -t patrikx3/openwrt-insomnia .