language: node_js
cache:
    npm: false
node_js:
- lts/*
services:
- docker
before_script:
- npm install -g grunt-cli npm
- docker build -t patrikx3/openwrt-insomnia:base ./openwrt-base
script:
- docker build -t patrikx3/openwrt-insomnia .
env:
  global:
    secure: uaDmSmuWPz+JbhHcsyPnulpnEPOjsZToOsq6NxnlIDYp0PIP4fKPj1v4xYb1EI7VKNrCWjl/3YoXx7iMIKLMhtkdCU8WX+FzuJGJv1DmiazVkBrxrKZUul39csB5vNjv8VhCBEEGgcpEbO75f/wms/kp33zUWmgUhLyu3zRzIIlhkgOcR4oAIMVfqYiyHi9GT90raAL82M1moJRLtqhD5U2yP6lmSWG4t/RTVvnJzq6hHIP/m12+E9AS+f1bMX/mBVL/9i9fsJ59ePUPqMxP/sJU8+QKj+lvkGI02MqvIyGxTDIEft7iYd5QUhWs2hv6L9DV5BP1nBSBlqMd07LZZHiNvjbYgZqeP5Zz1vzoPsI6LGHH9sCGEOOGaxLf4Kzs3KZQjKAdxBYtoCrmXjSmqlNLkKcN74zImo30IVSyWxlyHwBwzdMnQleMqt4R4q+OfHNu1X6ynknq1j5cqSji0w643KQvUniBe44jo33vbloqFF4utOQsSAR+vaE/cU7BZgjI38/TSJtzQ3rPliI4EmILa/lbgQnReohH+vjhq8ehGD8K4v3WGH/MlV++sbyuL/sYzVaxNvhxV/UUpWhBnj/y5WoyAAD1K6A710TmVaVn2iAkOwYdB4HvZds0vie6vVqlT7RBiEW7YgcVk1frOCND/FEJpq3SZWk/sXkXR9o=
