#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

BUILD_DIR=build-openwrt
sudo rm -rf $DIR/$BUILD_DIR
sudo mkdir -p $DIR/$BUILD_DIR
sudo chmod 0777 -R $DIR/$BUILD_DIR
sudo chown $USER:$USER -R $DIR/$BUILD_DIR

export BUILD_DIR
