#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

source $DIR/openwrt-insomnia-lib

ROUTER_PROFILE="rpi-3"
ROUTER_TARGET="brcm2708"
ROUTER_SUB_TARGET="bcm2710"
FIRMWARE_NAME="insomnia"
IMAGE_BUILDER_FILE="/build/source/bin/targets/${ROUTER_TARGET}/${ROUTER_SUB_TARGET}/openwrt-imagebuilder-${OPENWRT_VERSION_TOTAL}-${ROUTER_TARGET}-${ROUTER_SUB_TARGET}.Linux-x86_64.tar.xz"

tag="rpi-3"


if [ -z "$1" ];
then
 build="corifeus"
else
 build=$1
fi

pre-build
feeds
setup-config-and-build $ROUTER_PROFILE $tag $build

if [ "$1" != "nosign" ] && [ "$2" != "nosign" ];
then
    $DIR/server-upload-delete-and-upload
fi

setup-image-builder-and-build $IMAGE_BUILDER_FILE $ROUTER_PROFILE $FIRMWARE_NAME $1
#setup-image-builder-and-build $IMAGE_BUILDER_FILE $ROUTER_PROFILE $FIRMWARE_NAME $1
post-build $1 $2

if [ "$1" != "nosign" ] && [ "$2" != "nosign" ];
then
    $DIR/server-upload-delete-and-upload
fi

final "$tag"
