#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

source $DIR/openwrt-insomnia-lib

tag="linksys-wrt"

#$DIR/make-linksys-wrt1900acs $1 $2

#if [ "$1" != "nosign" ] && [ "$2" != "nosign" ];
#then
#    $DIR/server-upload-delete-and-upload
#fi

#$DIR/make-linksys-wrt1900acs $1 $2
#$DIR/make-linksys-wrt3200acm $1 $2
$DIR/make-linksys-wrt1900acs-eduperez-mwlwifi $1 $2

if [ "$1" != "nosign" ] && [ "$2" != "nosign" ];
then
    $DIR/server-upload-delete-and-upload
fi

$DIR/make-linksys-wrt1900acs-eduperez-mwlwifi $1 $2
$DIR/make-linksys-wrt3200acm-eduperez-mwlwifi $1 $2

if [ "$1" != "nosign" ] && [ "$2" != "nosign" ];
then
    $DIR/server-upload-delete-and-upload
fi

final "$tag"

