#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

copy-scripts.sh

ROUTER_TARGET="mvebu"
ROUTER_SUB_TARGET="cortexa9"
ROUTER_ARCH="arm_cortex-a9_vfpv3-d16"
FIRMWARE_NAME="insomnia"
IMAGE_BUILDER_FILE_WITHOUT_EXTENSION="openwrt-imagebuilder-${OPENWRT_VERSION_TOTAL_IMAGEBUILDER}-${ROUTER_TARGET}-${ROUTER_SUB_TARGET}.Linux-x86_64"
IMAGE_BUILDER_FILE="/build/source/bin/targets/${ROUTER_TARGET}/${ROUTER_SUB_TARGET}/${IMAGE_BUILDER_FILE_WITHOUT_EXTENSION}.tar.xz"
ROUTER_PROFILE="linksys-wrt-multiple"

source $DIR/openwrt-insomnia-lib

tag="linksys-wrt"

if [ -z "$1" ];
then
 build="corifeus"
else
 build=$1
fi

#pre-build
#patches-and-feeds
#setup-config-and-build linksys-wrt-multiple $tag $build

#if [ "$1" != "nosign" ] && [ "$2" != "nosign" ];
#then
#    echo "OK"
#    $DIR/server-upload-delete-and-upload
#fi

image-builder-uncompress $IMAGE_BUILDER_FILE
echo "Image builder is uncompressed"

setup-image-builder-and-build uncompressed linksys_wrt1900acs $FIRMWARE_NAME $1
setup-image-builder-and-build uncompressed linksys_wrt3200acm $FIRMWARE_NAME $1
setup-image-builder-and-build uncompressed linksys_wrt32x $FIRMWARE_NAME $1

post-build $1 $2

#if [ "$1" != "nosign" ] && [ "$2" != "nosign" ];
#then
#    echo "OK"
#    $DIR/server-upload-delete-and-upload
#fi

final "$tag"
