#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

ROUTER_TARGET="mvebu"

#ROUTER_SUB_TARGET="cortexa9"
ROUTER_SUB_TARGET="generic"

FIRMWARE_NAME="insomnia-latest-mwlwifi"
#IMAGE_BUILDER_FILE_WITHOUT_EXTENSION="openwrt-imagebuilder-${OPENWRT_VERSION_TOTAL}-${ROUTER_TARGET}-${ROUTER_SUB_TARGET}.Linux-x86_64"
IMAGE_BUILDER_FILE_WITHOUT_EXTENSION="openwrt-imagebuilder-${OPENWRT_VERSION_TOTAL}-${ROUTER_TARGET}.Linux-x86_64"

IMAGE_BUILDER_FILE="/build/source/bin/targets/${ROUTER_TARGET}/${ROUTER_SUB_TARGET}/${IMAGE_BUILDER_FILE_WITHOUT_EXTENSION}.tar.xz"

ROUTER_PROFILE="linksys-wrt-kaloz-multiple"

source $DIR/openwrt-insomnia-lib

tag="linksys-wrt-kaloz"

if [ -z "$1" ];
then
 build="corifeus"
else
 build=$1
fi

pre-build
# disable patches, use raw
#patches-and-feeds
setup-config-and-build linksys-wrt-kaloz-multiple $tag $build

if [ "$1" != "nosign" ] && [ "$2" != "nosign" ];
then
    $DIR/server-upload-delete-and-upload
fi

image-builder-uncompress $IMAGE_BUILDER_FILE
echo "Image builder is uncompressed"

setup-image-builder-and-build uncompressed linksys-wrt1900acs $FIRMWARE_NAME $1
setup-image-builder-and-build uncompressed linksys-wrt3200acm $FIRMWARE_NAME $1

post-build $1 $2

if [ "$1" != "nosign" ] && [ "$2" != "nosign" ];
then
    $DIR/server-upload-delete-and-upload
fi

final "$tag"