#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

source $DIR/openwrt-insomnia-lib

rm -rf ~/.gnupg || true


tty=`basename $(tty)`

gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 95F12499
passphrase=$(cat /build/secure/passphrase.txt)
#show-passphrase
echo $passphrase | gpg --passphrase-fd 0 --import /build/secure/gpg/secret-signing-key.pgp
echo "use-agent" >> ~/.gnupg/gpg.conf
echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
touch ~/.gnupg/gpg-agent.conf
echo $passphrase | gpg --passphrase-fd 0 --import /build/secure/gpg/secret-signing-key.pgp

generate-firmware-dir

pushd $firmware_files_dir

rm $firmware_files_dir/sha256sums || true
rm $firmware_files_dir/sha256sums.gpg || true
rm $firmware_files_dir/sha256sums.asc || true

delete-firmware-openwrt-files

for file in $firmware_files
do
 if [[ -f $file ]]; then
        sha256sum $(basename $file) >> sha256sums
    fi
done

sha256sum -c --ignore-missing sha256sums
#show-passphrase
echo $passphrase | gpg --passphrase-fd 0 -a --detach-sign sha256sums
mv sha256sums.asc sha256sums.gpg
# gpg --status-fd 1 --with-fingerprint --verify "sha256sums.gpg" "sha256sums"

gpg --with-fingerprint --verify "sha256sums.gpg" "sha256sums"

#gpg --keyserver hkp://pool.sks-keyservers.net --fingerprint D52BBB6B --encrypt

packages=$(find /build/source/bin -name "Packages")
for pkg in $packages
do
 if [[ -f $pkg ]]; then
        echo $pkg
        usign -S -c "Openwrt Insomnia by patrikx3" -m $pkg -s /build/secure/usign/secret.key -p /build/secure/usign/public.key
        usign -V -m $pkg -p /build/secure/usign/public.key
 fi
done

popd
